### ISSUE TITLE
1º Milestone

### ISSUE THREAD

**Issue by letsaguiar** [letsaguiar/study-tracker#1]
# Study Tracker 1º Milestone

## Goal
Finish an usable version of the application

## Features
- [x] Create Practice Test module
- [ ] Create Performance module
- [x] Exchange database to SQLite
- [x] Move to a single Dockerfile to be published at github registry

## Bug fix
- [x] [Adjust user local timezone](https://github.com/letsaguiar/study-tracker/issues/2 )
- [x] [Adjust default value to subject update](https://github.com/letsaguiar/study-tracker/issues/3) 
- [x] [Adjust durantion display at study session table](https://github.com/letsaguiar/study-tracker/issues/4)

## Secondary Improvements
- [x] [Redesign study session create modal](https://github.com/letsaguiar/study-tracker/issues/5)
- [ ] [Testing Discovery - Backend and Frontend](https://github.com/letsaguiar/study-tracker/issues/6)
- [ ] Frontend Best Practices Discovery
- [ ] Statistics Discovery
