### ISSUE TITLE
2º Milestone

### ISSUE THREAD

**Issue by letsaguiar** [letsaguiar/study-tracker#15]
# Goal
Ajustar a aplicação de acordo com as necessidades dos estudantes brasileiros

# Features
- [ ] Dashboard (Estatísticas Semanais)
- [ ] Tempo Total de Estudos (card)
- [ ] Número Total de Exercícios (card)
- [ ] Percentual de Acertos (card)
- [ ] Tempo restante (em semanas) até o próximo exame (card)
- [ ] Tempo de Estudos por matéria (gráfico pizza)
- [ ] Tempo de Estudos por dia (gráfico linha)
- [ ] Últimos Exercícios (tabela com 5 registros)
- [ ] Últimos Simulados (table com 5 registros)

- [ ] Matérias
- [ ] Submatérias

- [ ] Sessões de Estudo
- [ ] Timer
- [ ] Pomodoro

- [ ] Exercícios

- [ ] Exames
- [ ] Simulados

- [ ] Estatísticas
- [ ] Tempo Total de Estudos (card)
- [ ] Número Total de Exercícios (card)
- [ ] Percentual de Acertos (card)
- [ ] Percentual de Acertos nos Exames (card)
- [ ] Tempo Total de Estudos / matéria (gráfico pizza)
- [ ] Exercícios / matéria (gráfico pizza)
- [ ] Percentual de acertos / matéria (gráfico pizza)
- [ ] Aproveitamento (percentual de acertos / tempo de estudo) / matéria
- [ ] Percentual de acertos / exame
- [ ] Evolução no tempo (Percentual de acertos nos exercícios e exames)
